header:
    title: 
    text: 
    button: Tell Me More
    buttonlink: "#services" # "#{section}" or "URL/page link"

services:
    title: "Science"
    text: "Science Goals and Objectives"
    section: services
    list:
      - title: "Science Goal"
        desc: "To reveal how small-scale ocean features affect large-scale weather and climate."
        icon: fas fa-cloud-rain #find more at https://fontawesome.com/icons
      - title: "Science Objective 1"
        desc: "Determine whether small-scale spatial variations in air-sea fluxes near warm ocean currents affect large-scale storm evolution and prediction of long-term weather."
        icon: fas fa-wind      
      - title: "Science Objective 2"
        desc: "Determine whether small-scale variations in the air-sea boundary layers contribute significantly to the large-scale air-sea exchange of heat and water."
        icon: fab fa-confluence

portfolio:
    title: "Mission Concept"
    text: "Fully polarimetric passive microwave radiometer with hyperspectral channels"
    section: portfolio
    

timeline:
    title: "About" 
    text: "Butterfly timeline"
    section: timeline
    events:
      - title: "Our Humble Beginnings"
        year: "2016"
        desc: "Engineer cold emails scientist...want to meet at AGU and talk about science?"
        image: assets/img/timeline/agu.png
        alt: 
        align: left
      - title: "Butterfly is born"
        year: "2017"
        desc: "A virtual team is created, a lot of online brainstorming...what is interesting science with big societal impact?"
        image: assets/img/timeline/brain.jpg
        alt: 
        align: right
      - title: "Earth Venture Instrument - EVI5 - internal JPL competition"
        year: "2018"
        desc: "We like your science, but, you are an EVM trying to fit into an EVI, patience young skywalker...."
        image: assets/img/timeline/yoda.jpg
        alt: image alt text
        #align: #default is left       
      - title: "Earth Venture Mission - 3 - NASA competition"
        year: "2020"
        desc: "Drinking from a firehose. Electrical or chemical spacecraft propulsion? Rigid or deployable antenna? Science Tracability Matrix whaaaa??"
        image: assets/img/timeline/firehose.jpg
        alt: 
        align: right
    end: "Be Part <br> of Our <br> Story!"

about:
    title: "About Us"
    text: "Our science team is open source, open data, and open science. We are cloud-based and looking for community solutions to advance air-sea interactions research. We want to work with *you*!"
    section: about

clients:
    title: "Partners" 
    text: "Institutional Partners"
    section: clients
    max-height: 100px
    horizontal-scrolling: "no" #"yes/no"
    list:
      - title: "Farallon Institute"
        url: https://faralloninstitute.org
        logo: assets/img/clients/FI.png
      - title: "Jet Propulsion Laboratory"
        url: https://www.jpl.nasa.gov/
        logo: assets/img/clients/JPL.jpg
      - title: "Woods Hole Oceanographic Institution"
        url: http://whoi.edu/
        logo: assets/img/clients/whoi.jpg
      - title: "Ball Aerospace"
        url: https://www.ball.com/aerospace
        logo: assets/img/clients/ball.png
      - title: "Florida State University"
        url: https://www.fsu.edu/
        logo: assets/img/clients/FSU.png
      - title: "Penn State University"
        url: https://www.psu.edu
        logo: assets/img/clients/penn.png
      - title: "Scripps Institute of Oceanography"
        url: https://scripps.ucsd.edu/
        logo: assets/img/clients/sio.png
      - title: "University of Colorado"
        url: https://www.colorado.edu/
        logo: assets/img/clients/ucolorado.png     
team:
    title: "OUR AMAZING TEAM"
    text: "Introducing...."
    subtext: Specialists in Oceanography, Meteorology, Satellites, Weather, open science, open code, and open source software! 
    section: team
    people:
      - name: "Chelle Gentemann"
        role: "Principal Investigator"
        image: assets/img/team/gentemann.jpg
        social:
          - url: https://twitter.com/chellegentemann
            icon: fab fa-twitter
          - url: https://github.com/cgentemann
            icon: "fab fa-github"
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/gentemann.md
            icon: fas fa-file-alt
      - name: "Carol Anne Clayson"
        role: "Deputy Principal Investigator"
        image: assets/img/team/clayson.jpg
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/clayson.md
            icon: fas fa-file-alt
      - name: "Tony Lee"
        role: "Project Scientist"
        image: assets/img/team/lee.png
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/lee.md
            icon: fas fa-file-alt
      - name: "Shannon Brown"
        role: "Deputy Project Scientist"
        image: assets/img/team/brown.jpg
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/brown.md
            icon: fas fa-file-alt
      - name: "Kelly Lombardo"
        role: "Co-Investigator - Lead Science Objective 1A"
        image: assets/img/team/lombardo.jpg
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/lombardo.md
            icon: fas fa-file-alt
      - name: "Rhys Parfitt"
        role: "Co-Investigator - Deputy Lead Science Objective 1A"
        image: assets/img/team/parfitt.jpg
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/parfitt.md
            icon: fas fa-file-alt
      - name: "Hyodae Seo"
        role: "Co-Investigator - Lead Science Objective 1B"
        image: assets/img/team/seo.png
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/seo.md
            icon: fas fa-file-alt
      - name: "Aneesh Subramanian"
        role: "Co-Investigator - Deputy Lead Science Objective 1B"
        image: assets/img/team/subramanian.jpg
        social:
          - url: https://twitter.com/aneeshcs
            icon: fab fa-twitter
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/subramanian.md
            icon: fas fa-file-alt
      - name: "Sarah Gille"
        role: "Co-Investigator - Lead Science Objective 2"
        image: assets/img/team/gille.jpg
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/gille.md
            icon: fas fa-file-alt
      - name: "Tom Farrar"
        role: "Co-Investigator - Deputy Lead Science Objective 2"
        image: assets/img/team/farrar.jpg
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/farrar.md
            icon: fas fa-file-alt
      - name: "Mark Bourassa"
        role: "Co-Investigator - Lead Cal/Val"
        image: assets/img/team/bourassa.jpg
        social:
          - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io/blob/master/assets/science_team_resumes/bourassa.md
            icon: fas fa-file-alt
      - name: "Mr. Bouncy"
        role: "Space Dog"
        image: assets/img/team/dog.jpg
         
contact:
    title: "Contact Us"
    text: "nasa-butterfly@faralloninstitute.org"
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"  
      - url: https://github.com/nasa-butterfly/nasa-butterfly.github.io
        icon: "fab fa-github"
      - url: https://instagram.com
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}

